title: "Projet SEO"
description: "description site"

baseurl: ""
url: "www.referencement-web.site" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
