title: "Projet SEO"
description: "description site"

baseurl: ""
url: "http://0.0.0.0:4000/" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
