title: "Référencement web, Google et Bing et leurs robots indexeurs"
description: "Comprendre le référencement SEO : comportement des robots indexeurs de Google et Bing, interprétation du no-follow et indexation mobile"

baseurl: ""
url: "www.referencement-web.site" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
