title: "Référencement SEO • Google et Bing"
description: "Articles scientifiques pour tout savoir sur le référencement SEO, comportement des robots indexeurs de Google et Bing, interprétation du no-follow, recherche mobile."

baseurl: ""
url: "www.referencement-web.site" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
